// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace agenda_consultorio.Migrations
{
    [DbContext(typeof(AgendaContext))]
    [Migration("20241204203344_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Consulta", b =>
                {
                    b.Property<string>("CPF")
                        .HasColumnType("text");

                    b.Property<DateTime>("DataConsulta")
                        .HasColumnType("timestamp with time zone");

                    b.Property<TimeSpan>("HoraInicial")
                        .HasColumnType("interval");

                    b.Property<TimeSpan>("HoraFinal")
                        .HasColumnType("interval");

                    b.HasKey("CPF", "DataConsulta", "HoraInicial");

                    b.ToTable("Consultas");
                });

            modelBuilder.Entity("Paciente", b =>
                {
                    b.Property<string>("CPF")
                        .HasColumnType("text");

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Idade")
                        .HasColumnType("integer");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("CPF");

                    b.ToTable("Pacientes");
                });

            modelBuilder.Entity("Consulta", b =>
                {
                    b.HasOne("Paciente", null)
                        .WithMany()
                        .HasForeignKey("CPF")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
